### ISSUE TITLE
Enderstorage Mod crashes game on title screen

### ISSUE THREAD

**Issue by TheNickofTime22** [DoughnutDev/DonutCraft#7]
Fresh install = crash
Reinstall = crash
disabling enderstorage = no crash
re-enabling enderstorage = crash
[crash-2022-06-04_08.17.10-client.txt](https://github.com/DoughnutDev/DonutCraft/files/8837071/crash-2022-06-04_08.17.10-client.txt)

**Comment by DoughnutDev** [comment]
This is an issue with your graphics card you have to make sure your graphics card is the default for games and not the integrated graphics from your cpu. I had an issue with another user and this crash and that was the issue. If you look at fix 3 on this guide that is how you fix it https://www.drivereasy.com/knowledge/how-to-fix-laptop-not-using-gpu/amp/

**Comment by TheNickofTime22** [comment]
> 

This solved it, thank you!
